// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with `pnpm generate`.
import { piece as audit } from "./slices/audit/handler.js";
import { slice as auditSlice } from "./slices/audit/module.js";
import { piece as notifications } from "./slices/notifications/handler.js";
import { slice as notificationsSlice } from "./slices/notifications/module.js";

export const slices = [auditSlice, notificationsSlice] as const;
export const pieces = [audit, notifications] as const;
