// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with `pnpm generate`.
import { piece as billing } from "./slices/billing/activities.js";
import { slice as billingSlice } from "./slices/billing/module.js";
import { piece as fulfillment } from "./slices/fulfillment/activities.js";
import { slice as fulfillmentSlice } from "./slices/fulfillment/module.js";

export const slices = [billingSlice, fulfillmentSlice] as const;
export const pieces = [billing, fulfillment] as const;
