import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { Err, Ok, TaggedError, type Result } from "unthrown";

const TRANSPORTS = ["controller.ts", "handler.ts", "activities.ts"] as const;

/** A `src/slices/*` directory does not conform to the one-transport, one-module shape a slice must have. */
export class SliceTreeInvalid extends TaggedError("SliceTreeInvalid")<{
  readonly directory: string;
  readonly problem: string;
}> {}

const camel = (dir: string): string =>
  dir.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Walks `<srcDir>/slices/*` and renders `slices.gen.ts`: every slice's
 * `module.ts` import plus a `slices` array, and every transport piece —
 * collected into a `pieces` array for `handler.ts`/`activities.ts`, or
 * re-exported by name for `controller.ts`, which a keyed HTTP router needs
 * addressable rather than positional.
 */
export const renderSlicesGen = (srcDir: string): Result<string, SliceTreeInvalid> => {
  const slicesDir = join(srcDir, "slices");
  const dirs = existsSync(slicesDir)
    ? readdirSync(slicesDir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .toSorted()
    : [];

  const imports: string[] = [];
  const reexports: string[] = [];
  const sliceNames: string[] = [];
  const pieceNames: string[] = [];
  const taken = new Set(["slices", "pieces"]);

  for (const dir of dirs) {
    if (!existsSync(join(slicesDir, dir, "module.ts"))) {
      return Err(
        new SliceTreeInvalid({ directory: dir, problem: "missing module.ts exporting `slice`" }),
      );
    }
    const transports = TRANSPORTS.filter((file) => existsSync(join(slicesDir, dir, file)));
    const [transport, extra] = transports;
    if (transport === undefined || extra !== undefined) {
      return Err(
        new SliceTreeInvalid({
          directory: dir,
          problem: `expected exactly one transport file (controller.ts | handler.ts | activities.ts), found ${transports.length}`,
        }),
      );
    }

    const name = camel(dir);
    if (!IDENTIFIER.test(name)) {
      return Err(
        new SliceTreeInvalid({
          directory: dir,
          problem: `camelCases to \`${name}\`, which is not a valid identifier`,
        }),
      );
    }
    const sliceName = `${name}Slice`;
    const pieceName = transport === "controller.ts" ? `${name}Controller` : name;
    for (const identifier of [pieceName, sliceName]) {
      if (taken.has(identifier)) {
        return Err(
          new SliceTreeInvalid({
            directory: dir,
            problem: `emits \`${identifier}\`, which another slice or a reserved export already claims`,
          }),
        );
      }
      taken.add(identifier);
    }
    if (transport === "controller.ts") {
      reexports.push(`export { piece as ${pieceName} } from "./slices/${dir}/controller.js";`);
    } else {
      const module = transport.replace(".ts", ".js");
      imports.push(`import { piece as ${pieceName} } from "./slices/${dir}/${module}";`);
      pieceNames.push(pieceName);
    }
    imports.push(`import { slice as ${sliceName} } from "./slices/${dir}/module.js";`);
    sliceNames.push(sliceName);
  }

  const lines = [
    "// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with `pnpm generate`.",
    ...imports,
    "",
    ...reexports,
    `export const slices = [${sliceNames.join(", ")}] as const;`,
    ...(pieceNames.length > 0
      ? [`export const pieces = [${pieceNames.join(", ")}] as const;`]
      : []),
  ];

  return Ok(`${lines.join("\n")}\n`);
};
