import { describe, expect } from "vitest";

import { renderSlicesGen } from "./render.js";
import { it } from "./test-fixtures.js";

describe("renderSlicesGen", () => {
  it("collects handler pieces into sorted slices and pieces arrays", ({ tree }) => {
    // GIVEN two handler slices, created out of order
    const src = tree.src([
      "slices/notifications/module.ts",
      "slices/notifications/handler.ts",
      "slices/audit/module.ts",
      "slices/audit/handler.ts",
    ]);
    // WHEN the tree is rendered
    const rendered = renderSlicesGen(src);
    // THEN the file imports both slices and both pieces, sorted by directory
    expect(rendered).toBeOkWith(
      `// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with \`pnpm generate\`.
import { piece as audit } from "./slices/audit/handler.js";
import { slice as auditSlice } from "./slices/audit/module.js";
import { piece as notifications } from "./slices/notifications/handler.js";
import { slice as notificationsSlice } from "./slices/notifications/module.js";

export const slices = [auditSlice, notificationsSlice] as const;
export const pieces = [audit, notifications] as const;
`,
    );
  });

  it("re-exports controller pieces by name instead of collecting an array", ({ tree }) => {
    // GIVEN two controller slices
    const src = tree.src([
      "slices/orders/module.ts",
      "slices/orders/controller.ts",
      "slices/customers/module.ts",
      "slices/customers/controller.ts",
    ]);
    // WHEN the tree is rendered
    const rendered = renderSlicesGen(src);
    // THEN each controller is a named re-export and there is no pieces array
    expect(rendered).toBeOkWith(
      `// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with \`pnpm generate\`.
import { slice as customersSlice } from "./slices/customers/module.js";
import { slice as ordersSlice } from "./slices/orders/module.js";

export { piece as customersController } from "./slices/customers/controller.js";
export { piece as ordersController } from "./slices/orders/controller.js";
export const slices = [customersSlice, ordersSlice] as const;
`,
    );
  });

  it("refuses a slice directory with no transport file", ({ tree }) => {
    // GIVEN a slice with a module but no controller/handler/activities
    const src = tree.src(["slices/orphan/module.ts"]);
    // WHEN the tree is rendered
    const rendered = renderSlicesGen(src);
    // THEN the error names the directory and the problem
    expect(rendered).toBeErrWith(
      expect.objectContaining({
        directory: "orphan",
        problem: expect.stringContaining("transport"),
      }),
    );
  });

  it("refuses a slice directory with no module.ts", ({ tree }) => {
    // GIVEN a slice with a handler but no module
    const src = tree.src(["slices/orphan/handler.ts"]);
    // WHEN the tree is rendered
    const rendered = renderSlicesGen(src);
    // THEN the error names the directory and the problem
    expect(rendered).toBeErrWith(
      expect.objectContaining({
        directory: "orphan",
        problem: expect.stringContaining("module.ts"),
      }),
    );
  });
});
