import { defineConfig } from "vitepress";

const SITE_DESCRIPTION =
  "A module-based dependency-injection container for TypeScript: ports as the vocabulary an application defines, providers bound at one edge, and Result instead of throws.";

const BASE = "/di/";
const SITE_URL = `https://btravstack.github.io${BASE}`;

// The guide is structured by the four Diátaxis modes (https://diataxis.fr/): a
// learning-oriented Tutorial, task-oriented How-to guides, information-oriented
// Reference, and understanding-oriented Explanation. One shared sidebar carries
// all four so any page can reach any other.
const GUIDE_SIDEBAR = [
  {
    text: "Tutorial",
    items: [{ text: "Getting started", link: "/tutorial/getting-started" }],
  },
  {
    text: "How-to guides",
    items: [
      { text: "Swap an adapter for tests", link: "/how-to/swap-an-adapter" },
      { text: "Manage a resource's lifetime", link: "/how-to/manage-a-resource" },
      { text: "Open a per-request scope", link: "/how-to/request-scope" },
      { text: "Build a plugin registry", link: "/how-to/plugin-registry" },
      { text: "Keep a port private", link: "/how-to/private-ports" },
    ],
  },
  {
    text: "Reference",
    items: [
      { text: "Ports", link: "/reference/ports" },
      { text: "Providers", link: "/reference/providers" },
      { text: "Modules", link: "/reference/modules" },
      { text: "Entry points", link: "/reference/entry-points" },
      { text: "Wiring defects", link: "/reference/wiring-defects" },
      { text: "API reference", link: "/api/" },
    ],
  },
  {
    text: "Explanation",
    items: [
      { text: "Why di?", link: "/explanation/why-di" },
      { text: "Compile errors, not surprises", link: "/explanation/compile-time-wiring" },
      { text: "Modules and privacy", link: "/explanation/modules-and-privacy" },
      { text: "Scopes and resource safety", link: "/explanation/scopes-and-resources" },
      { text: "Failures vs defects", link: "/explanation/failures-vs-defects" },
      { text: "Peer dependencies", link: "/explanation/peer-dependencies" },
    ],
  },
];

// The runnable packages under `examples/`. Unlike every fenced block in the
// guide, that code compiles and its specs run in CI.
const EXAMPLES_SECTION = {
  text: "Examples",
  items: [
    { text: "Overview", link: "/examples/" },
    { text: "Hexagonal order API", link: "/examples/hexagonal-order-api" },
    { text: "Request scope", link: "/examples/request-scope" },
    { text: "Plugin registry", link: "/examples/plugin-registry" },
  ],
};

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "di",
  description: SITE_DESCRIPTION,
  base: BASE,
  lang: "en-US",
  cleanUrls: true,

  // `docs/superpowers/` is local design scratch — git-ignored, and not part of
  // the published site. Without this VitePress renders whatever happens to be
  // sitting there into a page and a sitemap entry.
  srcExclude: ["superpowers/**"],

  // The API reference under /api/di/ is generated by TypeDoc and copied in at
  // build time; its cross-references use relative links TypeDoc resolves itself.
  ignoreDeadLinks: [/^\/api\//, /^\.\/index$/, /^\.\/[a-z-]+$/, /^\.\.\//],

  sitemap: {
    hostname: SITE_URL,
  },

  // Per-page canonical URL + Open Graph / Twitter title & description, so every
  // page shares a correct preview and avoids duplicate-content ambiguity.
  transformPageData(pageData) {
    if (!pageData.relativePath.endsWith(".md")) {
      return;
    }

    const normalizedPath = pageData.relativePath.replace(/^\/+/, "");
    // cleanUrls is true, so the public URL has no `.html` extension: strip
    // `index.md` to the directory and any other `.md` to the bare route.
    const canonicalUrl = `${SITE_URL}${normalizedPath}`
      .replace(/index\.md$/, "")
      .replace(/\.md$/, "");

    pageData.frontmatter ??= {};
    pageData.frontmatter.head ??= [];

    // The /api/ pages (except the hand-written overview) are TypeDoc output copied
    // in at build time — they have no source file in the repo, so "Edit this page"
    // would 404. docs/api/index.md is the one committed file there.
    if (pageData.relativePath.startsWith("api/") && pageData.relativePath !== "api/index.md") {
      pageData.frontmatter.editLink = false;
    }

    pageData.frontmatter.head.push(["link", { rel: "canonical", href: canonicalUrl }]);

    const pageTitle = pageData.title || pageData.frontmatter.title || "di";
    const pageDescription =
      pageData.description || pageData.frontmatter.description || SITE_DESCRIPTION;

    pageData.frontmatter.head.push(
      ["meta", { property: "og:url", content: canonicalUrl }],
      ["meta", { property: "og:title", content: pageTitle }],
      ["meta", { property: "og:description", content: pageDescription }],
      ["meta", { name: "twitter:title", content: pageTitle }],
      ["meta", { name: "twitter:description", content: pageDescription }],
    );
  },

  themeConfig: {
    logo: "/logo.svg",

    nav: [
      // The guide is organised by the four Diátaxis modes; the dropdown links
      // the entry page of each. See the sidebar for the full contents.
      {
        text: "Guide",
        items: [
          { text: "Tutorial", link: "/tutorial/getting-started" },
          { text: "How-to guides", link: "/how-to/swap-an-adapter" },
          { text: "Reference", link: "/reference/ports" },
          { text: "Explanation", link: "/explanation/why-di" },
        ],
      },
      { text: "Examples", link: "/examples/" },
      { text: "API", link: "/api/" },
      {
        text: "Changelog",
        link: "https://github.com/btravstack/di/releases",
      },
      // Back to the btravstack hub (links the docs up to the landing page).
      { text: "btravstack", link: "https://btravstack.github.io/" },
    ],

    sidebar: {
      // One shared sidebar across all four Diátaxis sections, so a reader can
      // move between Tutorial / How-to / Reference / Explanation from any page.
      ...Object.fromEntries(
        ["/tutorial/", "/how-to/", "/reference/", "/explanation/"].map((prefix) => [
          prefix,
          GUIDE_SIDEBAR,
        ]),
      ),
      // The examples carry the guide sidebar too, with their own section on
      // top: they are walkthroughs of the same material, so a reader landing on
      // one should still reach every page of the guide.
      "/examples/": [EXAMPLES_SECTION, ...GUIDE_SIDEBAR],
      "/api/": [
        {
          text: "API Reference",
          items: [
            { text: "Overview", link: "/api/" },
            { text: "@btravstack/di", link: "/api/di/" },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/btravstack/di" },
      { icon: "npm", link: "https://www.npmjs.com/package/@btravstack/di" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: `Copyright © ${new Date().getFullYear()} Benoit TRAVERS`,
    },

    search: {
      provider: "local",
    },

    // The reference pages are dense with `###`-level members; surfacing them in
    // the right-rail outline is what makes them navigable.
    outline: { level: [2, 3] },

    editLink: {
      pattern: "https://github.com/btravstack/di/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },

  vite: {
    // @btravstack/theme's entry imports `vitepress/theme` (which pulls in `.css`)
    // and its own `style.css`. VitePress externalizes node_modules deps in the SSR
    // build, so Node's ESM loader would hit those `.css` files and throw
    // ERR_UNKNOWN_FILE_EXTENSION. Bundling the theme through Vite handles the CSS.
    ssr: { noExternal: ["@btravstack/theme"] },
  },

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: `${BASE}logo.svg` }],
    ["meta", { name: "author", content: "Benoit TRAVERS" }],
    ["meta", { name: "robots", content: "index, follow" }],
    ["meta", { name: "application-name", content: "di" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "typescript, dependency injection, di, ioc, inversion of control, hexagonal architecture, ports and adapters, modules, container, errors as values, result, unthrown",
      },
    ],
    // Open Graph — og:title/description/url are added per page in transformPageData.
    // No og:image yet: the 1280x640 social card on the family template does not
    // exist for this package, and an SVG logo is not a valid og:image (X, Slack,
    // LinkedIn and Discord all refuse to render one — measured on the sibling
    // sites). Add the card and its four meta tags together when it is drawn.
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "di" }],
    ["meta", { property: "og:locale", content: "en_US" }],
    // Twitter Card — plain `summary` until the wide card image exists;
    // `summary_large_image` with no image renders nothing at all.
    ["meta", { name: "twitter:card", content: "summary" }],
    // JSON-LD structured data for better SEO
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: "@btravstack/di",
        description: SITE_DESCRIPTION,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Cross-platform",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        url: SITE_URL,
        author: {
          "@type": "Person",
          name: "Benoit TRAVERS",
        },
        programmingLanguage: {
          "@type": "ComputerLanguage",
          name: "TypeScript",
          url: "https://www.typescriptlang.org/",
        },
        keywords: "TypeScript, dependency injection, hexagonal architecture, modules, Result",
      }),
    ],
    // WebSite JSON-LD for proper site name display in Google search
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: "di",
        url: SITE_URL,
      }),
    ],
    // Organization JSON-LD for logo display in Google search
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Organization",
        name: "di",
        url: SITE_URL,
        logo: {
          "@type": "ImageObject",
          url: `${SITE_URL}logo.svg`,
        },
        sameAs: ["https://github.com/btravstack/di"],
      }),
    ],
  ],
});
