// Generate the per-package API reference into `api/<name>/`, one TypeDoc run
// per `typedoc.<name>.json`, concurrently. TypeDoc lives here rather than in
// each package because it needs its own TypeScript — see the root CLAUDE.md.
import { execFile } from "node:child_process";
import { globSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, "..");

// Run TypeDoc's JS entry under `process.execPath`, not the `.bin` shim (which is
// `typedoc.cmd` on Windows). Resolved via `package.json` — the only subpath its
// `exports` map allows.
const TYPEDOC = join(
  dirname(createRequire(import.meta.url).resolve("typedoc/package.json")),
  "bin",
  "typedoc",
);

// The order is DEPENDENCY order, which is information a glob cannot recover, so
// the list stays written down — but it is checked against the `typedoc.*.json`
// files on disk below rather than merely asked to stay in sync. Also mirrored by
// `@btravstack/docs#build`'s `dependsOn` in the root `turbo.json` and the
// `/api/` sidebar in `.vitepress/config.ts`.
const packages: readonly string[] = [
  "contract",
  "di",
  "config",
  "core",
  "testing",
  "observability",
  "cache",
  "mailer",
  "storage",
  "prisma",
  "http-server",
  "temporal-worker",
  "amqp-worker",
];

// The hub page named three PRE-RENAME packages and linked three routes that had
// never existed, and listed 8 of the 13 — for a year, because it was the one
// list with no mechanical check (issue #191). Both halves are checked now: the
// list against the configs on disk, and the page against the list, by generating
// it. `docs/api/index.md` is gitignored for the same reason `api/<name>/` is.
const configured = globSync(join(docsDir, "typedoc.*.json"))
  .map((file) => basename(file).slice("typedoc.".length, -".json".length))
  .sort();

const missing = configured.filter((name) => !packages.includes(name));
const extra = packages.filter((name) => !configured.includes(name));
if (missing.length > 0 || extra.length > 0) {
  console.error(
    "✗ build-api's package list disagrees with the typedoc configs on disk:" +
      (missing.length > 0 ? `\n  configured but not listed: ${missing.join(", ")}` : "") +
      (extra.length > 0 ? `\n  listed but not configured: ${extra.join(", ")}` : ""),
  );
  process.exit(1);
}

type Manifest = {
  readonly description?: string;
  readonly exports?: Readonly<Record<string, unknown>>;
};

/** A package's own `description`, and the subpaths its `exports` map declares. */
const manifestOf = (name: string): Manifest =>
  JSON.parse(
    readFileSync(join(docsDir, "..", "packages", name, "package.json"), "utf8"),
  ) as Manifest;

const subpathsOf = (manifest: Manifest): readonly string[] =>
  Object.keys(manifest.exports ?? {}).filter((key) => key !== "." && key !== "./package.json");

const entry = (name: string): string => {
  const manifest = manifestOf(name);
  const subpaths = subpathsOf(manifest);
  const extraEntries =
    subpaths.length === 0
      ? ""
      : ` Additional entry points: ${subpaths
          .map((subpath) => `\`@btravstack/${name}${subpath.slice(1)}\``)
          .join(", ")}.`;
  return `- **[\`@btravstack/${name}\`](/api/${name}/)** — ${manifest.description ?? ""}.${extraEntries}`;
};

const hub = `---
title: API reference
description: The generated reference for every published package — each exported symbol, its signature and its TSDoc.
---

<!-- Generated by docs/scripts/build-api.ts. Do not edit; edit the generator. -->

# API reference

Generated from the source with [TypeDoc](https://typedoc.org/) at build time —
every exported symbol, with its signature and TSDoc. One page per package,
listed in dependency order: \`contract\` and \`di\` depend on nothing here, then
\`config\` and \`core\`, then the harness, the observability starter, the three
application-service ports, the Prisma starter and the three transport starters
on top of \`core\`.

${packages.map(entry).join("\n")}

::: tip Looking for prose?
The generated pages document _signatures_. For what each package is **for**,
with its install line and worked examples, read
[Packages and install](/reference/packages) and the hand-written reference
under it; for _why_ the surface is shaped this way, read
[Why btravstack?](/explanation/why-btravstack).
:::
`;

writeFileSync(join(docsDir, "api", "index.md"), hub);
console.log(`✓ generated the API hub → api/index.md (${packages.length} packages)`);

const results = await Promise.allSettled(
  packages.map(async (name) => {
    await run(process.execPath, [TYPEDOC, "--options", `typedoc.${name}.json`], {
      cwd: docsDir,
    });
    return name;
  }),
);

let failed = false;

for (const [index, result] of results.entries()) {
  const name = packages[index];
  if (result.status === "fulfilled") {
    console.log(`✓ generated API docs for ${name} → api/${name}/`);
  } else {
    failed = true;
    const { stdout, stderr } = result.reason as { stdout?: string; stderr?: string };
    console.error(`✗ TypeDoc failed for ${name}`);
    if (stdout) console.error(stdout);
    if (stderr) console.error(stderr);
  }
}

if (failed) process.exit(1);
console.log("✅ API documentation generated.");
