// Generated by @btravstack/internal-slice-codegen — do not edit; regenerate with `pnpm generate`.
import { slice as customersSlice } from "./slices/customers/module.js";
import { slice as ordersSlice } from "./slices/orders/module.js";

export { piece as customersController } from "./slices/customers/controller.js";
export { piece as ordersController } from "./slices/orders/controller.js";
export const slices = [customersSlice, ordersSlice] as const;
